In [1]:
import numpy as np

In [2]:
a = np.random.randint(2, 10, (3, 3))
b = np.random.randint(10, 21, (3, 3))

In [3]:
a

array([[2, 8, 5],
       [9, 4, 9],
       [6, 7, 4]])

In [4]:
b

array([[15, 13, 17],
       [10, 12, 17],
       [11, 18, 13]])

In [5]:
c = a @ b
c

array([[165, 212, 235],
       [274, 327, 338],
       [204, 234, 273]])

In [6]:
np.max(c)

338